# Generated by Django 6.1.1 on 2026-10-06 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mandate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('mandant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandates_as_mandant', to=settings.AUTH_USER_MODEL)),
                ('steuerberater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mandates_as_steuerberater', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mandant', 'steuerberater')},
            },
        ),
    ]
